### PR TITLE
Add title and navigation box to preview

### PR DESCRIPTION
**Pull request by actiniumn404**
Hi.

I added the title and navigation box to the preview, along with some CSS snippets. I also added padding to the home page.

### CODE REVIEW

**Comment by epiccakeking** [comment]
Could you fix the line endings? Whenever the last newline is added/removed it makes the last line in the file get changed.

**Comment by actiniumn404** [comment]
Sorry, I feel dumb asking this, but, can you elaborate.

**Comment by epiccakeking** [comment]
Basically, every line in the file should terminated with the newline character (which often shows up as one blank line at the end of each file). Basically, make sure each file has one blank line at the end.

**Comment by actiniumn404** [comment]
Ah, I see. Thanks for telling me that. I fixed it.

**Pull request merged**
